version: "3.7"
services:
  gateway:
    build: .
    image: jgrothe/gateway
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
      - "keycloak.auth-server-url=http://127.0.0.1:8080"
      - "keycloak.enabled=false"
    ports:
      - "8088:8088"
    expose:
      - 8088
    container_name: gateway
    depends_on:
      - rabbitmq
  currency-service:
    image: jgrothe/currency-service
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    ports:
      - "8087:8087"
    expose:
      - 8087
    container_name: currency-service
    depends_on:
      - rabbitmq
  price-service:
    image: jgrothe/price-service
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    ports:
      - "8085:8085"
    expose:
      - 8085
    container_name: price-service
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
